project='lua-gainer-lib'
title='Lua GAINER library documentation'
description='A library to control GAIENR I/O educational board'
style='!new'
format='discount'
backtick_references=false
file='lib/gainer.lua'
dir='docs'
readme='docs/README.md'
kind_names={topic='Manual',script='Programs'}
examples = {
    'examples/advancedAnalogRead.lua',
    'examples/analogRead.lua',
    'examples/analogSampling.lua',
}

